/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from "@aztec/aztec.js/addresses";
import {
  type AbiType,
  type AztecAddressLike,
  type ContractArtifact,
  EventSelector,
  decodeFromAbi,
  type EthAddressLike,
  type FieldLike,
  type FunctionSelectorLike,
  loadContractArtifact,
  loadContractArtifactForPublic,
  type NoirCompiledContract,
  type U128Like,
  type WrappedFieldLike,
} from "@aztec/aztec.js/abi";
import {
  Contract,
  ContractBase,
  ContractFunctionInteraction,
  type ContractInstanceWithAddress,
  type ContractMethod,
  type ContractStorageLayout,
  DeployMethod,
} from "@aztec/aztec.js/contracts";
import { EthAddress } from "@aztec/aztec.js/addresses";
import { Fr, Point } from "@aztec/aztec.js/fields";
import { type PublicKey, PublicKeys } from "@aztec/aztec.js/keys";
import type { Wallet } from "@aztec/aztec.js/wallet";
import TenochcaContractArtifactJson from "../../target/tenochca_contract-Tenochca.json" with { type: "json" };
export const TenochcaContractArtifact = loadContractArtifact(
  TenochcaContractArtifactJson as NoirCompiledContract,
);

/**
 * Type-safe interface for contract Tenochca;
 */
export class TenochcaContract extends ContractBase {
  private constructor(instance: ContractInstanceWithAddress, wallet: Wallet) {
    super(instance, TenochcaContractArtifact, wallet);
  }

  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(address: AztecAddress, wallet: Wallet) {
    return Contract.at(
      address,
      TenochcaContract.artifact,
      wallet,
    ) as Promise<TenochcaContract>;
  }

  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, owner: AztecAddressLike) {
    return new DeployMethod<TenochcaContract>(
      PublicKeys.default(),
      wallet,
      TenochcaContractArtifact,
      TenochcaContract.at,
      Array.from(arguments).slice(1),
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(
    publicKeys: PublicKeys,
    wallet: Wallet,
    owner: AztecAddressLike,
  ) {
    return new DeployMethod<TenochcaContract>(
      publicKeys,
      wallet,
      TenochcaContractArtifact,
      TenochcaContract.at,
      Array.from(arguments).slice(2),
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof TenochcaContract["methods"]>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<TenochcaContract["methods"][M]>
  ) {
    return new DeployMethod<TenochcaContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      TenochcaContractArtifact,
      TenochcaContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? "constructor",
    );
  }

  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return TenochcaContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(
      TenochcaContractArtifactJson as NoirCompiledContract,
    );
  }

  public static get storage(): ContractStorageLayout<
    | "owner"
    | "is_registered"
    | "registered_artists"
    | "total_artists"
    | "artist_totals"
  > {
    return {
      owner: {
        slot: new Fr(1n),
      },
      is_registered: {
        slot: new Fr(3n),
      },
      registered_artists: {
        slot: new Fr(4n),
      },
      total_artists: {
        slot: new Fr(5n),
      },
      artist_totals: {
        slot: new Fr(6n),
      },
    } as ContractStorageLayout<
      | "owner"
      | "is_registered"
      | "registered_artists"
      | "total_artists"
      | "artist_totals"
    >;
  }

  /** Type-safe wrappers for the public methods exposed by the contract. */
  declare public methods: {
    /** constructor(owner: struct) */
    constructor: ((owner: AztecAddressLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** donate(artist: struct, amount: integer) */
    donate: ((
      artist: AztecAddressLike,
      amount: bigint | number,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_artist_at_index(index: integer) */
    get_artist_at_index: ((
      index: bigint | number,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_artists_count() */
    get_artists_count: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_owner() */
    get_owner: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_total_received(artist: struct) */
    get_total_received: ((
      artist: AztecAddressLike,
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** is_registered(artist: struct) */
    is_registered: ((artist: AztecAddressLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((
      message_ciphertext: FieldLike[],
      message_context: {
        tx_hash: FieldLike;
        unique_note_hashes_in_tx: FieldLike[];
        first_nullifier_in_tx: FieldLike;
        recipient: AztecAddressLike;
      },
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** register_profile() */
    register_profile: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** sync_private_state() */
    sync_private_state: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;
  };
}
